### ISSUE TITLE
Skin enigma2-plugin-skins-bundesligafhd-raed crashes enigma2

### ISSUE THREAD

**Issue by petrkr** [OpenVisionE2/RAED-Mod-Skins#4]
When skin "enigma2-plugin-skins-bundesligafhd-raed" is installed. Enigma will crash everytime during start-up (not need even select that skin). Only uninstall this package will help.

```
<  7210.840> [PluginComponent] Plugin  Extensions/WebInterface failed to load: No module named plugin
<  7210.840> [PluginComponent] Plugin probably removed, but not cleanly in /usr/lib/enigma2/python/Plugins/Extensions/WebInterface
<  7210.857> Traceback (most recent call last):
<  7210.858>   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 57, in action
<  7210.858>   File "/usr/lib/enigma2/python/Screens/PluginBrowser.py", line 315, in requestClose
<  7210.858>   File "/usr/lib/enigma2/python/Components/PluginComponent.py", line 77, in readPluginList
<  7210.858> AttributeError: 'NoneType' object has no attribute 'path'
<  7210.858> [ePyObject] (CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap instance at 0xb06cd760>>,('WizardActions', 'back')) failed)
<  7214.069> [gRC] main thread is non-idle! display spinner!
Killed
root@sf4008:~# 
```

[enigma2_crash_1582465410.log](https://github.com/OpenVisionE2/RAED-Mod-Skins/files/4241318/enigma2_crash_1582465410.log)

**Comment by fairbird** [comment]
The problem not from skin ..

> <  7210.840> [PluginComponent] Plugin  Extensions/WebInterface failed to load: No module named plugin
<  7210.840> [PluginComponent] Plugin probably removed, but not cleanly in /usr/lib/enigma2/python/Plugins/Extensions/WebInterface

We did not use WebInterface on openvision images we use openwebif..
also I have test skins now on my dm920 with new clean build image and skin works without any error ..

**Comment by petrkr** [comment]
It starts when this skin is installed and stops when I will do opkg remove. I did little research of code of it and there is some extra python code compared to other skins in this repository.

```
sourcedate=2020-02-16
branch=develop
rev=7f63f9a
visionversion=9.3
visionrevision=r95
```

**Comment by fairbird** [comment]
I will test it again latter ...

**Comment by fairbird** [comment]
Skin updated .. You can try now
https://github.com/OpenVisionE2/RAED-Mod-Skins/commit/bea00f4ed279f9f38936fd67e29dc739018f1faa

**Comment by petrkr** [comment]
I will try whenever i will go home (like 4hours)

**Comment by petrkr** [comment]
```
root@sf4008:~# opkg install enigma2-plugin-skins-bundesligafhd-raed
Upgrading enigma2-plugin-skins-bundesligafhd-raed from git27+1465756-r0 to git29+602974b on root
Downloading http://10.200.0.5/all/enigma2-plugin-skins-bundesligafhd-raed_git29+602974b-r0_all.ipk.
Configuring enigma2-plugin-skins-bundesligafhd-raed.
```

even after update it still crashes on that 

```
<   506.947> EXCEPTION IN PYTHON STARTUP CODE:
<   506.947> ------------------------------------------------------------
<   506.947> Traceback (most recent call last):
<   506.947>   File "/usr/lib/enigma2/python/mytest.py", line 687, in <module>
<   506.948>     runScreenTest()
<   506.948>   File "/usr/lib/enigma2/python/mytest.py", line 482, in runScreenTest
<   506.948>     plugins.readPluginList(resolveFilename(SCOPE_PLUGINS))
<   506.948>   File "/usr/lib/enigma2/python/Components/PluginComponent.py", line 77, in readPluginList
<   506.948> AttributeError: 'NoneType' object has no attribute 'path'
<   506.948> ------------------------------------------------------------
```


[enigma2-plugin-skins-bundesligafhd-raed.md5sum.txt](https://github.com/OpenVisionE2/RAED-Mod-Skins/files/4247389/enigma2-plugin-skins-bundesligafhd-raed.md5sum.txt)

**Comment by petrkr** [comment]
Actually `enigma2-plugin-skins-mxsline-raed` plugin/skin causes same issue

**Comment by petrkr** [comment]
hmm,, don't ask me why, but even I updated submodules and sources, it kept old files.. I found problem with lines in def Plugins which will return PluginDescription only if skin was selected..
But in your huge commit I see you fix that lines... But even in latest ipk (also with latest git commit tag) still have old files..

Maybe bug of build system?

**Comment by petrkr** [comment]
Aha I see it now.. you meanwhile commited another two commits. And I remember there was "6" at begin of git hash when I build it afternoon. and latest commit also starts on "6"... So let's try recompile

**Comment by petrkr** [comment]
OK.. 

```
root@sf4008:~# opkg install enigma2-plugin-skins-bundesligafhd-raed
Upgrading enigma2-plugin-skins-bundesligafhd-raed from git29+602974b-r0 to git31+679c37b on root
Downloading http://10.200.0.5/all/enigma2-plugin-skins-bundesligafhd-raed_git31+679c37b-r0_all.ipk.
Configuring enigma2-plugin-skins-bundesligafhd-raed.
```

```
root@sf4008:~# opkg install enigma2-plugin-skins-mxsline-raed                   
Installing enigma2-plugin-skins-mxsline-raed (git31+679c37b) on root
Downloading http://10.200.0.5/all/enigma2-plugin-skins-mxsline-raed_git31+679c37b-r0_all.ipk.
Configuring enigma2-plugin-skins-mxsline-raed.
```

latest works fine!

Good work

Actually that idea show configuration menu only if skin is selected (not only installed) is good.. But it should return some "dummy" plugin description so it will no crash. But for now, this is good solution aswell

Again 2am, so I go to sleep

**Comment by fairbird** [comment]
More fix in plugin (Now If skin not active plugin will be hide)  
https://github.com/OpenVisionE2/RAED-Mod-Skins/commit/4be6d71c03e170e92bfce7dedde584559a422295
